on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/RockstarsRevealTheme/assets/css

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.9
        with:
          source: theme/source/rockstars.scss
          destination: /tmp/RockstarsRevealTheme/assets/css/rockstars.css

      - name: Move compiled CSS to path within pr-pages branch
        run: mv /tmp/RockstarsRevealTheme/assets/css/rockstars.css assets/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            assets/rockstars.css
