# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
jobs:
  build_css:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/RockstarsRevealTheme/assets/css

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.9
        with:
          source: theme/source/rockstars.scss
          destination: rockstars.css

      - name: Install and Build 🔧
        run: |
          npm install --no-optional reveal-md
          ./node_modules/.bin/reveal-md --css rockstars.css --assets-dir assets --static build example/index.md
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          #- uses: "marvinpinto/action-automatic-releases@latest"
          #  with:
          #    repo_token: "${{ secrets.GITHUB_TOKEN }}"
          #    automatic_release_tag: "latest"
          #    prerelease: true
          #    title: "Development Build"
          #    files: |
          #      assets/rockstars.css
